### ISSUE TITLE
Change the title and put a logo instead

### ISSUE THREAD

**Issue by easybeau** [lumeland/theme-simple-blog#26]
Hello,

Thank you for this theme and lume ssg. I like to use the cms, too.

How to change the title and put a logo instead ?

Thanks for your help,
Best wishes,

Isabelle

**Comment by oscarotero** [comment]
Hi.
In `_data.yml` you can edit the `home.welcome` variable to include a image. For example:

```yml
home:
  welcome: |
    <img src="/logo.png" width=300 height=200>

```
